site_name: GLAM Workbench

site_description: 'A collection of tools and examples to help you work with data from galleries, libraries, archives, and museums'
site_author: 'Tim Sherratt'
site_url: 'https://glam-workbench.net/'

# Repository
#repo_name: 'squidfunk/mkdocs-material'
repo_name: glam-workbench.github.io
repo_url: 'https://github.com/GLAM-Workbench/glam-workbench.github.io'
edit_uri: "edit/master/docs/"

# Copyright
copyright: 'Copyright &copy; 2022 <a href="/contributors/">GLAM Workbench contributors</a>.<br/>Documentation is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.<br/>Original code is licensed under an <a href="https://opensource.org/licenses/MIT">MIT Licence</a>.'

# Configuration
theme:
  name: 'material'
  custom_dir: 'overrides'
  language: 'en'
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - announce.dismiss
    # - toc.integrate
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: material/hammer-wrench
#    repo: material/source-repository
  include_search_page: false
  search_index_only: true

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/glam-workbench'
      name: 'GLAM Workbench on GitHub'
    - name: '@wragge on Twitter'
      icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/wragge'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/101dhhacks/'
      name: '101 DH Hacks on Facebook'
    - icon: 'fontawesome/solid/rss'
      link: 'https://updates.timsherratt.org/categories/glamworkbench/'
      name: 'Latest GLAMWorkbench news!'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
#  - 'https://hypothes.is/embed.js'

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: ['includes', '../site/includes']
      check_paths: True
  - attr_list
  - md_in_html
  - toc_ext:
      permalink: true
  - meta
  - def_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - macros:
        on_undefined: keep
    - redirects:
        redirect_maps:
            'trove_newspapers.md': 'trove-newspapers.md'
            'name-search.md': 'https://glam-name-indexes-yajhxrvxsa-ts.a.run.app/'
            supporters.md: get-involved/supporters.md

nav:
    - Home: index.md
    - About:
        - about.md
        - Presentations: presentations.md
        - awards.md
        - Citations: citations.md
        - Get involved!:
            - get-involved/index.md
            - get-involved/supporters.md
            - Add a link: get-involved/add-links.md
            - Improve the documentation: get-involved/editing-documentation.md
            - Contribute code: get-involved/contribute-code.md
            - Develop a new repository: get-involved/developing-repositories.md
            - contributors.md
    - Help:
        - getting-started.md
        - Running notebooks:
            - using-binder.md
            - using-reclaim-cloud.md
            - using-nectar.md
            - using-docker.md
            - using-python.md
        - Help videos: https://www.youtube.com/playlist?list=PLAclcciEeCD2z2BWQ2r3xD_Q8c05HppfP
        - Suggest a topic: https://github.com/GLAM-Workbench/glam-workbench.github.io/issues
        - Ask a question: https://ozglam.chat/c/glam-workbench/8
        - Book a chat: https://calendly.com/timsherratt/30minchat
    - GLAM data:
        - Australia:
            - glam-data-list.md
            - Open data portals:
                - glam-data-portals.md
                - glam-datasets-from-gov-portals.md
            - csv-explorer.md
            - GLAM Name Index Search: name-search.md
    - Trove:
        - trove.md
        - trove-newspapers.md
        - Trove newspaper & gazette harvester:
            - trove-harvester/index.md
            - trove-harvester/harvester-web-app.md
            - Using the Trove Harvester: trove-harvester/using-troveharvester.md
            - Displaying results in Datasette: trove-harvester/display-harvest-results-in-datasette.md
            - Exploring harvested data: trove-harvester/exploring-troveharvester-data.md
            - Exploring harvested texts: trove-harvester/exploring-troveharvester-text.md
        - Trove books:
            - trove-books/index.md
            - Harvesting text from digitised books: trove-books/harvesting-text-of-digitised-books.md
            - Metadata for digital works: trove-books/metadata-for-digital-works.md
            - Harvesting text from Internet Archive: trove-books/harvesting-text-from-books-in-ia.md
            - trove-books/counting-words-and-phrases.md
            - trove-books/recipe-generator.md
            - Exploring Trove's digitised books: trove-books/exploring-digitised-books-adel-rahmani.md
            - OCRd text from Trove books: trove-books/ocrd-text-from-trove-books.md
            - CSV of digital books in Trove: trove-books/csv-books-in-digital-form.md
            - Government publications in digital form: trove-books/government-publications-in-digital-form.md
            - OCRd text from Australian books in IA: trove-books/ocrd-text-from-ia.md
            - CSV of Australian books in IA: trove-books/csv-australian-books-in-ia.md
        - Trove journals:
            - trove-journals/index.md
            - Create a list of digitised journals: trove-journals/create-list-digitised-journals.md
            - Get OCRd text from a journal: trove-journals/get-ocrd-text-from-digitised-journal.md
            - Get OCRd text from all journals: trove-journals/get-ocrd-text-from-all-journals.md
            - Get cover images from a journal: trove-journals/get-covers-from-digitised-journal.md
            - Finding cartoons in the Bulletin: trove-journals/finding-editorial-cartoons-in-bulletin.md
            - Harvest Parliament press releases: trove-journals/harvest-parliament-press-releases.md
            - Topic modelling Parliament press releases: trove-journals/topic-modelling-parliament-press-releases.md
            - CSV list of digital journals: trove-journals/csv-digital-journals.md
            - CSV list of journals with OCR: trove-journals/csv-journals-with-ocr.md
            - OCRd text from all journals: trove-journals/ocrd-text-all-journals.md
            - trove-journals/bulletin-cartoons-collection.md
            - Politicians talking about 'refugees': trove-journals/politicans-press-releases-refugees.md
            - Politicians talking about COVID: trove-journals/politicans-press-releases-covid.md
        - trove-lists.md
        - trove-maps.md
        - trove-music.md
        - Trove images:
            - trove-images/index.md
            - Rights statements applied to images: trove-images/use-of-rights-statements.md
            - CSV of rights applied to images: trove-images/csv-image-rights-by-institution.md
            - CSV of rights applied to out-of-copyright photos: trove-images/csv-out-of-copyright-photos-rights-by-institution.md
        - trove-unpublished.md
        - trove-random.md
    - digitalnz.md
    - Archives:
        - anu-archives.md
        - NAA:
            - recordsearch.md
            - naa-wap.md
            - naa-asio.md
        - nsw-state-archives.md
        - National Archives of NZ:
            - archway.md
        - qsa.md
    - Heritage:
        - Heritage Council of Victoria:
            - heritage-council-of-victoria/index.md
            - heritage-council-of-victoria/introduction-victorian-heritage-api.md
    - Libraries:
        - State Library of NSW:
            - Tribune negatives:
                - records-of-resistance.md
                - facial-detection.md
                - image-tagging.md
        - slsa.md
        - slv.md
        - lac.md
    - Web archives:
        - web-archives/index.md
        - web-archives/timegates-timemaps-mementos.md
        - web-archives/exploring-ia-cdx-api.md
        - web-archives/comparing-cdx-apis.md
        - web-archives/timemaps-vs-cdx.md
        - Get a Memento: web-archives/get-memento.md
        - Find all versions of a web page: web-archives/get-all-versions.md
        - Harvest text from web pages: web-archives/harvesting-text.md
        - Harvest data about a domain: web-archives/harvesting-domain-data.md
        - Explore Powerpoints from a domain: web-archives/exploring-powerpoints.md
        - Explore all subdomains from gov.au: web-archives/exploring-govau-subdomains.md
        - Compare versions of a page: web-archives/compare-page-versions.md
        - Observe change in a page over time: web-archives/observing-change-over-time.md
        - Create full-page screenshots: web-archives/create-screenshots.md
        - Create a series of screenshots: web-archives/create-screenshots-over-time.md
        - Display changes in page text: web-archives/display-changes-in-text.md
        - Find when text appears: web-archives/find-when-text-appears.md
        - Harvest of subdomains under gov.au: web-archives/harvest-of-govau-subdomains.md
        - Unique gov.au subdomains split into parts: web-archives/govau-subdomains-split.md
        - List of unique gov.au subdomains: web-archives/govau-subdomains-surt.md
        - Visualisations of gov.au subdomains: web-archives/govau-subdomains-visualisations.md
    - Museums:
        - nma.md
        - tepapa.md
        - museumsvictoria.md
    - Government:
        - Australia:
            - hansard.md
            - pm-transcripts.md
    - Useful tools:
        - Useful tools: glam-tools/index.md
        - CloudStor nested links: glam-tools/cloudstor-share-nested-links.md
        - CloudStor using WebDAV: glam-tools/cloudstor-access-via-webdav.md
    - More resources:
        - more-glam-notebooks.md
        - glam-tools-interfaces.md
    - Browse by tag: tags.md
    - Latest news!: https://updates.timsherratt.org/categories/glamworkbench/

