site_name: GLAM Workbench

site_description: 'A collection of tools and examples to help you work with data from galleries, libraries, archives, and museums'
site_author: 'Tim Sherratt'
site_url: 'https://glam-workbench.net/'

# Repository
#repo_name: 'squidfunk/mkdocs-material'
repo_name: GLAM-Workbench
repo_url: 'https://github.com/GLAM-Workbench/'
edit_uri: "docs/edit/master/docs/"

# Copyright
copyright: 'Copyright &copy; 2021 <a href="https://timsherratt.org">Tim Sherratt</a>. This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.'

# Configuration
theme:
  name: 'material'
  custom_dir: 'overrides'
  language: 'en'
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: material/hammer-wrench
#    repo: material/source-repository
  include_search_page: false
  search_index_only: true

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/glam-workbench'
      name: 'GLAM Workbench on GitHub'
    - name: '@wragge on Twitter'
      icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/wragge'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/101dhhacks/'
      name: '101 DH Hacks on Facebook'
    - icon: 'fontawesome/solid/rss-square'
      link: 'https://updates.timsherratt.org/categories/glamworkbench/'
      name: 'Latest GLAMWorkbench news!'

extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - meta

plugins:
    - search:
        separator: "[\\s\\-,:!=\\[\\]()\"/]+|\\.(?!\\d)|&[lg]t;|(?!\\b)(?=[A-Z][a-z])"
        indexing: 'titles'
    - redirects:
        redirect_maps:
            'trove_newspapers.md': 'trove-newspapers.md'
            'name-search.md': 'https://glam-name-indexes-yajhxrvxsa-ts.a.run.app/'
    - snippet:
        base_path: docs
    - git-latest-tag

nav:
    - Home: index.md
    - About:
        - about.md
        - presentations.md
        - awards.md
        - supporters.md
    - Help:
        - getting-started.md
        - Running notebooks:
            - using-binder.md
            - using-reclaim-cloud.md
            - using-nectar.md
            - using-docker.md
        - 'Help videos': https://www.youtube.com/playlist?list=PLAclcciEeCD2z2BWQ2r3xD_Q8c05HppfP
        - more-glam-notebooks.md
        - glam-tools-interfaces.md
    - Data sources:
        - Australia:
            - glam-data-list.md
            - Data portals:
                - glam-data-portals.md
                - glam-datasets-from-gov-portals.md
            - csv-explorer.md
    - Trove:
        - trove.md
        - trove-newspapers.md
        - trove-harvester.md
        - trove-books.md
        - trove-journals.md
        - trove-lists.md
        - trove-maps.md
        - trove-music.md
        - trove-images.md
        - trove-unpublished.md
        - trove-random.md
    - digitalnz.md
    - Archives:
        - anu-archives.md
        - NAA:
            - recordsearch.md
            - naa-wap.md
            - naa-asio.md
        - nsw-state-archives.md
        - National Archives of NZ:
            - archway.md
        - qsa.md
    - Libraries:
        - State Library of NSW:
            - Tribune negatives:
                - records-of-resistance.md
                - facial-detection.md
                - image-tagging.md
        - slsa.md
        - slv.md
        - lac.md
    - web-archives.md
    - Museums:
        - nma.md
        - tepapa.md
        - museumsvictoria.md
    - Government:
        - Australia:
            - hansard.md
            - pm-transcripts.md
    - GLAM Name Index Search: name-search.md
    - suggest-a-topic.md
    - ask-a-question.md
